In [1]:
import numpy as np

# Exercice 1

In [2]:
valeur=np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Exercice 2

In [5]:
valeur=np.array([3.14, 2.17, 0, 1, 2], dtype=int)

In [6]:
valeur

array([3, 2, 0, 1, 2])

# Exercise 3 : Working with Multi-Dimensional Arrays

In [9]:
valeur=np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

In [10]:
valeur

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Exercise 4 : Creating Multi-Dimensional Array with Random Numbers

In [11]:
valeur=np.random.rand(4,5)

In [12]:
valeur

array([[0.78804844, 0.69112674, 0.89332336, 0.10527419, 0.8536365 ],
       [0.35241325, 0.03431512, 0.69301038, 0.94538143, 0.25431131],
       [0.11591959, 0.44596893, 0.82929242, 0.01102026, 0.43706782],
       [0.4193506 , 0.24095293, 0.04581101, 0.01186518, 0.87185087]])

#  Exercise 5 : Indexing Arrays

In [14]:
valeur=np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])

In [15]:
valeur[1,:]

array([20, 21, 22, 23, 24])

#  Exercise 6 : Reversing elements

In [18]:
valeur=np.array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [20]:
valeur[::-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Exercise 7 : Identity Matrix

In [21]:
valeur=np.array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#  Exercise 8 : Simple Aggregate Funcs

In [ ]:
valeur=np.array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [26]:
moy=np.mean(valeur)
somme=np.sum(valeur)
print(f"somme {somme}")
print(f"moyenne {moy}")

somme 4.0
moyenne 0.25


# Exercise 9 : Create Array and Change its Structure

In [33]:
valeur=np.random.randint(1,21,size=20)

In [35]:
valeur

array([ 5,  1,  6, 12,  2, 20,  5,  1, 13, 18, 17, 19,  9, 12, 19, 17,  3,
        4, 13,  1], dtype=int32)

In [36]:
valeur.reshape(4,5)

array([[ 5,  1,  6, 12,  2],
       [20,  5,  1, 13, 18],
       [17, 19,  9, 12, 19],
       [17,  3,  4, 13,  1]], dtype=int32)

# Exercise 10 : Conditional Selection of Values

In [37]:
valeur=np.random.randint(1,21,size=20)

In [40]:
valeur

array([17, 17,  3, 10,  7,  3,  9, 11, 16, 13, 13, 18,  8,  2, 18,  9, 10,
       11, 14,  3], dtype=int32)

In [41]:
valeur[valeur%2==1]

array([17, 17,  3,  7,  3,  9, 11, 13, 13,  9, 11,  3], dtype=int32)