# Exercice 1

In [1]:

import numpy as np

In [6]:
# Create a 3x3 matrix and perform the following operations:

#Calculate the determinant.
#Find the inverse of the matrix.

matrix=np.random.rand(3,3)


In [13]:
determinant=np.linalg.det(matrix)
inv_matrix=np.linalg.inv(matrix)

In [16]:
display(determinant)
display(inv_matrix)


np.float64(-0.1418974992806114)

array([[-0.0429861 , -3.54298619,  2.07251853],
       [-0.92687893,  3.16285266,  0.04520365],
       [ 1.59510429,  0.78786641, -1.51352948]])

# Exercise 2 : Statistical Analysis

In [22]:
data=np.arange(50)

moy=np.mean(data)
med=np.median(data)
ect=np.std(data)

# Exercice 3: Date Manipulation

In [23]:
d=np.arange(2,9)

In [24]:
d

array([2, 3, 4, 5, 6, 7, 8])

In [42]:
import numpy as np

data_time=np.arange("2023-01","2023-12", dtype="datetime64[D]")

# Exercise 4 : Data Manipulation with NumPy and Pandas

In [63]:
my_data=np.random.randn(3,4)
d=np.linspace(3,9,3)


In [67]:
my_data
select=my_data[my_data>0]

In [69]:
moy=np.mean(select)
som=np.sum(select)

# Exercise 5 : Image Representation

In [79]:
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt

img = Image.open("Image.png")  

arr = np.array(img)                          # convertir en tableau NumPy
print(arr.shape)   # (5, 5)
print(arr.dtype)   # uint8
print(arr)         # la matrice ci-dessus


(650, 1280, 4)
uint8
[[[  9  10  15 255]
  [  8  10  14 254]
  [  8  10  14 254]
  ...
  [ 29  57 138 254]
  [ 27  59 144 254]
  [ 22  63 155 255]]

 [[  8  10  14 255]
  [  9  10  15 255]
  [  9  11  16 255]
  ...
  [ 21  62 155 254]
  [ 19  64 160 255]
  [ 19  64 161 255]]

 [[  8  10  15 255]
  [  8  10  14 255]
  [  8  10  15 254]
  ...
  [ 19  64 160 255]
  [ 19  64 161 255]
  [ 19  64 160 255]]

 ...

 [[  1   1   1 255]
  [  0   0   0 255]
  [  1   1   1 255]
  ...
  [ 15  52 121 255]
  [ 15  51 121 254]
  [ 16  52 122 255]]

 [[  0   0   0 255]
  [  0   0   0 255]
  [  1   1   1 254]
  ...
  [ 15  51 121 254]
  [ 16  52 122 255]
  [ 15  51 121 255]]

 [[  0   0   0 255]
  [  0   0   0 255]
  [  0   0   0 255]
  ...
  [ 15  52 121 255]
  [ 15  52 121 255]
  [ 15  51 121 254]]]


# Exercise 6 : Basic Hypothesis Testing